# Generated by Django 4.2.7 on 2026-08-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
